package base;

import org.openqa.selenium.By;

public class OpportunitiesLocators extends TestSetup {
    public static final By opportunities = By.xpath("//*[starts-with(text(),'Opportunities')]");
    public static final By opportunitiesManageLeads = By.xpath("//*[starts-with(text(),'Manage Leads')]");
    public static final By opportunitiesManageDeals = By.xpath("//*[starts-with(text(),'Manage Deals')]");
    public static final By addLeadButton = By.xpath("//button[@class='button_blue bgcolor-unset p0 btn-transitions mrgt1-2 mb_10']");
    public static final By leadForCompany = By.xpath("//select[@class='form-control ng-untouched ng-pristine ng-valid']");
    public static final By pipelineId = By.id("createdForPipelineId");
    public static final By pipelineStageId = By.id("createdForPipelineStageId");
    public static final By addleadCommentId =By.id("leadComment");
    public static final By firstNameId= By.xpath("//input[@id='First_Name']");
    public static final By lastNameId= By.xpath("//input[@id='Last_Name']");
    public static final By companyId= By.xpath("//input[@id='Company']");
    public static final By emailId= By.xpath("//input[@id='Email']");
    public static final By phoneNumberId = By.xpath("//input[@id='Phone_Number']");
    public static final By websiteId = By.xpath("//input[@id='Website']");
    public static final By address = By.xpath("//textarea[@class='form-control ng-tns-c35-3 ng-pristine ng-valid ng-touched']");
    public static final By cityId = By.xpath("//input[@id='City']");
    public static final By stateId = By.xpath("//input[@id='State']");
    public static final By countryId= By.xpath("//input[@id='Country']");
    public static final By postalCodeId = By.xpath("//input[@id='Postal_Code']");
    public static final By jobTitleId = By.xpath("//input[@id='Title']");
    public static final By amountId = By.xpath("//input[@id='Amount']");
    public static final By industryId = By.xpath("//input[@id='Industry']");
    public static final By regionID = By.xpath("//input[@id='Region']");
    public static final By saveLead =By.id("saveLead");
    public static final By campaignView = By.xpath("//i[@class='fa fa-folder-open p10']");
    public static final By listView = By.xpath("//i[@class='fa fa-th-list p10']");
    public static final By eMailReport = By.xpath("//i[@class='fas fa-file-export p10']");
    public static final By leadSearch = By.xpath("//input[@class='form-control pr-pl ml ng-untouched ng-pristine ng-valid']");
    public static final By leadsSearchButton = By.xpath("//button[@class='search-box-item-click top mb_v_search top2']");
    public static final By leadsSearchCancel = By.xpath("//button[@class='glyphicon glyphicon-remove search-box-item-clear ng-tns-c65-3']");
    public static final By leadsFilter = By.xpath("//i[@class='fa fa-filter p10']");
    public static final By totalLeads = By.xpath("//div[@class='desc' and contains(text(),'Total Leads')]");
    public static final By wonLeads = By.xpath("//div[@class='desc' and contains(text(),'Won Leads')]");
    public static final By lostDeals = By.xpath("//div[@class='desc' and contains(text(),'Lost Leads')]");
    public static final By convertedLeads = By.xpath("//div[@class='desc' and contains(text(),'Converted Leads')]");
    // The below values are not unique. To use it uniquely, first search for the lead then perform what action you want to perform. or use index
    public static final By leadView = By.xpath("(//i[@class='fa fa-eye mr5 IconCustomization'])[3]");
    public static final By leadViewComments = By.xpath("//textarea[contains(@class,'ng-pristine ng-valid')]");
    public static final By leadViewCommentsSubmit = By.xpath("//button[@class='btn btn-primary transition mb5']");
    public static final By leadViewCloseButton = By.xpath("//a[@class='pull-right close-circle mrg1']");
    public static final By leadEdit = By.xpath("(//i[@class='fa fa-edit mr5 IconCustomization'])[3]");
    public static final By leadUpdate = By.xpath("//button[@id='saveLead']");
    public static final By leadComments = By.xpath("(//i[@class='fa fa-comments IconCustomization'])[3]");
    public static final By leadCommentTxtArea = By.xpath("//textarea[contains(@class,'ng-pristine ng-valid')]");
    public static final By leadCommentSubmit = By.xpath("//button[@class='btn btn-primary transition mb5']");
    public static final By leadCommentWindowClose = By.xpath("//a[@class='close-circle' and @title='Close']");
    public static final By leadDelete = By.xpath("(//i[@class='fa fa-trash-o trashIconCustomization'])[3]");
    public static final By leadDeleteReject = By.xpath("//button[@class='swal2-cancel styled']");
    public static final By leadDeleteApprove = By.xpath("//button[@class='swal2-confirm styled']");
    public static final By leadReacordCnt = By.xpath("(//span[starts-with(text(),'Total Records :')])[1]");
    public static final By leadNextPage = By.xpath("//i[@class='fa fa-angle-right' and contains(@title,'Next')]");
    public static final By leadLastPage = By.xpath("//i[@class='fa fa-angle-double-right' and contains(@title,'Last')]");
    public static final By leadPreviousPage = By.xpath("(//i[@class='fa fa-angle-left' and contains(@title,'Previous')])[1]");
    public static final By leadFirstPage = By.xpath("//i[@class='fa fa-angle-double-left' and @title='First']");
    public static final By leadPageCntDrpDwn = By.xpath("(//select[contains(@class,'form-control margin-top pointer mt_10 ')])[1]");
    public static final By registerDeal =By.xpath("(//button[@class='button_blue bgcolor-unset'])[4]");
    //#########################################################################################################
    public static final By addDealButton = By.xpath("//button[@class='button_blue bgcolor-unset p0 btn-transitions mrgt1-2']");
    public static final By dealCompany = By.xpath("//select[@id='createdForCompanyId']");
    public static final By dealPipeline = By.xpath("//select[@id='createdForPipelineId']");
    public static final By dealPipeLineStage = By.xpath("//select[@id='createdForPipelineStageId']");
    public static final By dealComment = By.xpath("//textarea[@id='dealComment']");
    public static final By dealAttachdrpDwn = By.xpath("//button[@class='btn Btn-Green mb_btn']");
    //# below xpath, if we update the numeric value, corresponding record will we get
    public static final By dealAttachaContact = By.xpath("//input[@id='contactCheckBox-4']");
    //# Attach Contact index+1 is more or less index value
    public static final By dealContactMoreOrLess = By.xpath("(//button[@class='border-btn-small lightgray-btn'])[5]");
    public static final By dealAttachSelected = By.xpath("//button[@class='button_blue button_disabled bgcolor-unset']");
    public static final By closeAttachContactWindow = By.xpath("//button[@class='close-circle']");
    public static final By searchContact = By.xpath("//input[@class='form-control pr-pl ml ng-pristine ng-valid ng-touched']");
    public static final By closeSearchContact = By.xpath("//button[@class='search-box-item-click top mb_v_search']");
    public static final By changeContact = By.xpath("//button[@class='button_blue bgcolor-unset p0 btn-transitions']");
    public static final By detachContact = By.xpath("(//button[@class='btn Btn-Gray neg_mrg_top4'])[2]");
    public static final By dealAttachLead = By.xpath("//input[@id='leadCheckBox-4']");
    public static final By viewLead = By.xpath("(//a[@id='lead'])[2]");
    public static final By attachSelectedLeadButton = By.xpath("//button[@id='saveLead']");
    public static final By searchLead = By.xpath("//input[@class='form-control pr-pl ml ng-untouched ng-pristine ng-valid']");
    public static final By searchLeadButton = By.xpath("//button[@class='search-box-item-click top mb_v_search']");
    public static final By dealType = By.xpath("//input[@id='Deal_Type']");
    public static final By dealName = By.xpath("//input[@id='Deal_Name']");
    public static final By dealAmount = By.xpath("//input[@id='Amount']");
    public static final By saveDeal = By.xpath("//button[@id='saveDeal']");
    public static final By dealCampaignView = By.xpath("//i[@class='fa fa-folder-open p10']");
    public static final By dealListView = By.xpath("//i[@class='fa fa-th-list p10']");
    public static final By dealsEmailReport = By.xpath("//i[@class='fas fa-file-export p10']");
    public static final By dealCloseDate = By.xpath("//div[contains(@class,'flatpickr-calendar animate showTimeInput open arrowBottom')]//div[@class='dayContainer']//span[@class='flatpickr-day ']");
    public static final By selectCloseDate = By.xpath("//input[@id='flat-picker']");
}
